### ISSUE TITLE
Automaticly closes after opening spotify, (v.0.3.0)

### ISSUE THREAD

**Issue by Hoomaaaan** [OpenByteDev/burnt-sushi#12]
Runned it as admin, installed it with the .msi installer, and also with the exe. One time it just said Injecting in spotify....... and never injected, i waited a solid 15mins. And now nothing shows in console

**Comment by OpenByteDev** [comment]
What version of spotify do you have installed?

**Comment by Swargwarn** [comment]
> 

I have the same issue.
Version:
Spotify for Windows (64 bit)
1.2.16.947.gcfbaa410

**Comment by OpenByteDev** [comment]
Could you paste the log from `%APPDATA%\OpenByte\BurntSushi\BurntSushi.log` here?

**Comment by Swargwarn** [comment]
> Could you paster the log from `%APPDATA%\OpenByte\BurntSushi\BurntSushi.log` here?

Interestingly it seems to be working fine now, I don't think I changed anything. Burnt Sushi doesn't close and ads seem to be blocked. here's the log anyway.

**[INFO] BurntSushi v0.3.0
[INFO] Looking for Spotify...
[INFO] Found Spotify (PID=15128)
[INFO] Loading filter config...
[DEBUG] Looking for filter config according to cli args...
[DEBUG] Looking for filter config next to executable...
[DEBUG] Looking for filter config at 'D:\Firefox Downloads\filter.toml'
[DEBUG] Loading default filter config...
[INFO] Preparing blocker...
[DEBUG] Looking for blocker according to cli args...
[DEBUG] Looking for blocker next to executable...
[DEBUG] Looking for blocker at 'D:\Firefox Downloads\BurntSushiBlocker_x64.dll'
[DEBUG] Looking for existing blocker in temporary directory...
[DEBUG] Looking for blocker at 'C:\Users\PCName\AppData\Local\OpenByteDev\BurntSushi v0.3.0\BurntSushiBlocker_x64.dll'
[DEBUG] Found blocker at 'C:\Users\PCName\AppData\Local\OpenByteDev\BurntSushi v0.3.0\BurntSushiBlocker_x64.dll'
[INFO] Injecting blocker...
[DEBUG] Starting RPC...
[INFO] Blocker up and running!
[INFO] Connected to 127.0.0.1:49330
[INFO] No new release found**

**Comment by OpenByteDev** [comment]
Do you still have the same issue @Hoomaaaan ?

**Comment by testdev123456** [comment]
same issue here.
( I tried both msi and exe )
Spotify latest version

It seems unstable, Sometimes spotify is not even running, 
I run burntsushi and few seconds later crashes.  sometimes runs OK ! 

Isn't it a good idea to make this app a Service on Windows? that way if it crashes, ti runs backs again automatically.

**Comment by Meganium97** [comment]
Can confirm this issue persists.

**Comment by Meganium97** [comment]
> same issue here. ( I tried both msi and exe ) Spotify latest version
> 
> It seems unstable, Sometimes spotify is not even running, I run burntsushi and few seconds later crashes. sometimes runs OK !
> 
> Isn't it a good idea to make this app a Service on Windows? that way if it crashes, ti runs backs again automatically.

@testdev123456 might want to consider this?
http://nssm.cc/
Basically turns any exe into a service - seems to be working perfectly. Unfortunately I don't have access to the console but I don't mind that for now.

**Comment by 1wass** [comment]
Hi, I've been having the same issue!  It worked for me until recently ive found it ending task by itself.  Idk how to fix this, and I've tried uninstalling and reinstalling, but to no avail.
