### ISSUE TITLE
Is non-functional as of 3/10/2024

### ISSUE THREAD

**Issue by FoxxClawz** [OpenByteDev/burnt-sushi#14]
when used with current spotify version, visual ads still appear.

**Comment by 1wass** [comment]
I also get spotify ads interrupting my listening.  Ive found with task manager it ends itself every time I try and start it up.  Please fix!!!!

**Comment by Migue8gl** [comment]
Same as @1wass. Does not even launch, if it does I don't see it in task manager.

**Comment by Trace6x** [comment]
Same problem here, hearing ads on Spotify again!

**Comment by OpenByteDev** [comment]
Fixed in [0.3.1](https://github.com/OpenByteDev/burnt-sushi/releases/tag/0.3.1)

**Comment by 1wass** [comment]
TYSM DAWG
