### ISSUE TITLE
Can you get it to unlock the lyrics too ?

### ISSUE THREAD

**Issue by minanagehsalalma** [OpenByteDev/burnt-sushi#17]
I mean it won't be that far from what the tool already does : \

![image](https://github.com/OpenByteDev/burnt-sushi/assets/20546638/b8fd67f8-7856-4403-b6f3-527b50aca4a7)

**Comment by OpenByteDev** [comment]
That largely depends on how it is implemented, because all BurntSushi does is blocking Spotify from loading any banners or audio ads. I would assume that this won't work in this case.

**Comment by OpenByteDev** [comment]
related to [#176](https://github.com/abba23/spotify-adblock/issues/176)

**Comment by OpenByteDev** [comment]
Im similarily gonna mark this out of scope
