### ISSUE TITLE
Instructions on how to build this

### ISSUE THREAD

**Issue by Thomas-678** [OpenByteDev/burnt-sushi#4]
Hi. Can you provide an instruction on how to build this application? (preferably from the perspective of after installing Rust for the first time)
Full disclosure, I don't know much about Rust, so I could be doing something wrong.
I tried to run "cargo build" inside the burnt-sushi folder and I got some errors.
I tried to resolve the errors one by one, like installing [capnp](https://capnproto.org/) and using "cargo +nightly build" instead. And there's still more build error.
Can you let us know what command you used to build this app? And is there any special configurations involved?

**Comment by OpenByteDev** [comment]
Building should work with the newest nightly like you mentioned with just capnp installed. What errors are you getting?

**Comment by Thomas-678** [comment]
The error is "can't find crate for `core`"
Then I ran rustup target add i686-pc-windows-msvc, and the build ran without issue.

**Comment by OpenByteDev** [comment]
Ah yes, the injectes blocker has to be build for x86 like Spotify is.
