### ISSUE TITLE
It does not work.

### ISSUE THREAD

**Issue by RevanAnders** [OpenByteDev/burnt-sushi#5]
I have tried it many times. Open Spotify, open Burnt Sushi. The icon works, in the taskbar, says Hello! and everything.
The ads keep on coming. And after a while, Burnt Sushi closes itself anyways without me doing anything. It used to work fine not too long ago.

**Comment by tomkc** [comment]
Stopped working after latest spotify update.

**Comment by OpenByteDev** [comment]
Can you try again with version [0.2.0](https://github.com/OpenByteDev/burnt-sushi/releases/tag/0.2.0)?

**Comment by RevanAnders** [comment]
> Can you try again with version [0.2.0](https://github.com/OpenByteDev/burnt-sushi/releases/tag/0.2.0)?

Confirmed as working as of today :)

**Comment by tomkc** [comment]
So far so good for over 2 hrs of using.
