### ISSUE TITLE
version 0.2.0 crashing from time to time

### ISSUE THREAD

**Issue by tomkc** [OpenByteDev/burnt-sushi#6]
After few days of using new version i've noticed burntsushi to be crashing 1-4 times a day over few hours of using. I'm noticing it by  return of spotify advertisements.  Is there a way to run bruntsushi with redirecting console messages to some log file?

**Comment by OpenByteDev** [comment]
Can you try to start the console by right clicking the system tray icon and post the log here once it crashes?

**Comment by tomkc** [comment]
I don't know what happened/changed in my configuration (maybe some windows/other component update) but since my report and few days of running burntsushi i didn't have single crash.

**Comment by Meganium97** [comment]
Can confirm this issue. After it crashes, the burntsushi icon refuses to do anything, I can't even right click it to show console. After force killing it and reopening it, it functions perfectly fine, for about an hour, until it crashes again. However as of recently, it hasn't been opening on boot for some reason.

**Comment by OpenByteDev** [comment]
Please confirm if this still happens with version 0.3.0

**Comment by Meganium97** [comment]
Not at home ATM, will start testing once I get back.

**Comment by Meganium97** [comment]
issue looks to be resolved with the latest version!

**Comment by Meganium97** [comment]
Issue came back up, alongside the issue of it closing when spotify opens.
