### ISSUE TITLE
Closing after spotify is open. Happens after 28th July 2023 Update.

### ISSUE THREAD

**Issue by nyaivu** [OpenByteDev/burnt-sushi#9]

**Comment by Cariyla** [comment]
Seconded, Spotify now seems to automatically terminate the program whenever it is running in the background, keeping the console open seems to work as a workaround for now but isn't ideal.

Edit: Never mind also doesn't work, stays open slightly longer that way but also gets terminated eventually.

**Comment by Merigold117** [comment]
Same here, just updated the app and having the same issue

**Comment by Bokayy** [comment]
What a joke. How does Spotify close my programs in the background without admin privileges? I run BS as admin BTW. Sorry for asking this question in what might be the wrong place but I believe it might be relevant to solving this problem.

**Comment by MAguiarP** [comment]
Same

**Comment by MAguiarP** [comment]
I fixed it, deleting it and re-downloading it with a different name in the executable.

**Comment by Merigold117** [comment]
> I fixed it, deleting it and re-downloading it with a different name in the executable.

Wait, did you rename the exe file or something else?

**Comment by MAguiarP** [comment]
> > I fixed it, deleting it and re-downloading it with a different name in the executable.
> 
> Wait, did you rename the exe file or something else?

renamed the exe and add in exclusion list windows defender.

**Comment by Sylvanbain** [comment]
doesnt work

> > > I fixed it, deleting it and re-downloading it with a different name in the executable.
> > 
> > 
> > Wait, did you rename the exe file or something else?
> 
> renamed the exe and add in exclusion list windows defender.

Doesn't work. I've tried renaming and adding both the exe and the dll in the exclusion, but BurntSushi is still terminated

**Comment by MAguiarP** [comment]
Strange, did you deactivate smart screen?

**Comment by MAguiarP** [comment]
> adding

Strange, did you deactivate smart screen?

**Comment by Sylvanbain** [comment]
> Strange, did you deactivate smart screen?

Sorry but I don't even know what smart screen is

**Comment by Trace6x** [comment]
Same issue over here, renaming exe/adding to windows exclusion made no difference for me either.
(I use EZblocker as an alternative but it just mutes ads rather than removing them)

**Comment by Cariyla** [comment]
Renaming the exe did nothing for me either, using any version of Spotify from before July 28th and re-installing that every time it updates (once every couple days) works for now but is obviously only a workaround and will also stop working eventually.

**Comment by MAguiarP** [comment]
something in Spotify app is blocking the injector, well, I found another way "fix", open the exe, and in the footer click in "show console" leave the opened, and open Spotify, the icon in footer will disappear but the console won't, will be continue working.

**Comment by MAguiarP** [comment]
Remembering, I'm not dev of this app, so. i can't change any lines.

**Comment by tomkc** [comment]
same here, but it works when starting burntsushi before launching spotify.

**Comment by Trace6x** [comment]
> 

This didn't work for me, console gets stuck on injecting...

**Comment by Trace6x** [comment]
> something in Spotify app is blocking the injector, well, I found another way "fix", open the exe, and in the footer click in "show console" leave the opened, and open Spotify, the icon in footer will disappear but the console won't, will be continue working.

This didn't work for me console gets stuck on injecting blocker...

**Comment by MAguiarP** [comment]
> > something in Spotify app is blocking the injector, well, I found another way "fix", open the exe, and in the footer click in "show console" leave the opened, and open Spotify, the icon in footer will disappear but the console won't, will be continue working.
> 
> This didn't work for me console gets stuck on injecting blocker...

Jesus man, have you at least tested if the advertisements continue to appear after the songs?, what a difficulty.

**Comment by tomkc** [comment]
> > something in Spotify app is blocking the injector, well, I found another way "fix", open the exe, and in the footer click in "show console" leave the opened, and open Spotify, the icon in footer will disappear but the console won't, will be continue working.
> 
> This didn't work for me console gets stuck on injecting blocker...

well it doesnt work always for me too, additionaly sometimes powershell get really high cpu usage after starting burnt sushi with console and then running spotify

**Comment by Trace6x** [comment]
> > > something in Spotify app is blocking the injector, well, I found another way "fix", open the exe, and in the footer click in "show console" leave the opened, and open Spotify, the icon in footer will disappear but the console won't, will be continue working.
> > 
> > 
> > This didn't work for me console gets stuck on injecting blocker...
> 
> Jesus man, have you at least tested if the advertisements continue to appear after the songs?, what a difficulty.

Jesus man, of course I did, have you at least tested to see if your workaround actually works before posting it as a solution? What a difficutly.

**Comment by Ju1-js** [comment]
As much as I love this project, I switched to using https://github.com/amd64fox/SpotX temporarily since the ads were getting annoying. I’ll probably switch back after burnt-sushi updates. But [SpotX](https://github.com/amd64fox/SpotX) works if anyone simply wants to block ads.

Edit: New update released, lets gooo.

**Comment by muggerfugger** [comment]
> As much as I love this project, I switched to using https://github.com/amd64fox/SpotX temporarily since the ads were getting annoying. I’ll probably switch back after burnt-sushi updates. But [SpotX](https://github.com/amd64fox/SpotX) works if anyone simply wants to block ads.

thanks. works perfectly.

**Comment by BozoAncientWizard** [comment]
Guys it happened to me too, all i do to fix it is close both spotify and BurntSushi, then start Burnt sushi and open its console and after that i open spotify back up and works normally. Just dont close the console and you should be fine i think.
